### ISSUE TITLE
[ Docs ] Github Project 및 template 생성

### ISSUE THREAD

**Issue by kimwest00** [TeamFair/meokQ-android#1]
## 📍Todo 
> Github Project 및 커스튬

### .github 하위 파일 생성
 - [x] Issue, PR template
 - [x] (보류)workflow 설정
 
### Project 생성 및 Issue 설정
- [x] Project 생성
- [x] Issue Label 수정
- [x] Milestone 생성및 연결
  - 로그인 개발 이후에 전체 마일스톤 설정 <- Jira - Github plugin 찾아보기
  - 우선 레이아웃, Project Setting만 설정해두었습니다!
- [x] Git Branch Protection Rule 설정
  - feat/ 설정말고 develop에 적용

### Wiki docs
- [ ] commit convention
- [ ] branch , Issue, PR

## To Collaborators
workflow 설정의 경우 아직 Github Action 관련하여 학습이 조금 필요해 아직 설정하지 않았습니다 ;)
